apiVersion: v1
kind: ReplicationController
metadata:
  name: router
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: ## Image is dynamically set by `make set-image` as part of dev deployment ##
        imagePullPolicy: Always
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          hostPort: 80
        - containerPort: 6443
          hostPort: 443
        - containerPort: 2222
          hostPort: 2222
        - containerPort: 9090
          hostPort: 9090
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 1
          timeoutSeconds: 1
