apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
    routable: "true"
    app: nginx
  annotations:
    router.deis.io/domains: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: apache
  namespace: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: apache
  labels:
    routable: "true"
    app: apache
  annotations:
    # Demonstrates a subdomain of the platform's domain as well as a custom domain
    router.deis.io/domains: apache,httpd.example.com
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache
